package model;

import java.time.LocalDate;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * Exam
 *
 * <p>Data class representing a graded exam. Getters, an all-args constructor, {@code equals},
 * {@code hashCode}, and {@code toString} are generated by Lombok.
 *
 * @author Daniel Appenmaier
 * @version 1.0
 *
 */
@Getter
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class Exam {

   /** The date on which the exam took place. */
   private final LocalDate examDate;
   /** The grade achieved, typically on a scale from 1.0 (best) to 5.0 (fail). */
   private double grade;

}
