package model;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * Student
 *
 * <p>Data class representing a student. Getters, an all-args constructor, {@code equals},
 * {@code hashCode}, and {@code toString} are generated by Lombok.
 *
 * @author Daniel Appenmaier
 * @version 1.0
 *
 */
@Getter
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class Student {

   /** The unique matriculation number of the student. */
   private final String id;
   /** The full name of the student. */
   private String name;

}
